### ISSUE TITLE
プロジェクトページをカスタムできるようにしたい

### ISSUE THREAD

**Issue by orekyuu** [GitThrow/GitThrow#32]
プロジェクトページ全般の色のテーマとか背景画像設定できるようにして、プロジェクト管理者の好みで痛くできるようにしたい

**Comment by shift02** [comment]
背景画像設定のイメージってこんな感じであっていますか？

![im](https://cloud.githubusercontent.com/assets/6204699/18379113/a77ff146-76ab-11e6-85dc-5e7c70bd8831.png)

**Comment by orekyuu** [comment]
サイドバーとかが浮いちゃうので透過出来るようにすればそれっぽくなるのかなー？
イメージ的にはそんな方針であってます！

**Comment by orekyuu** [comment]
実装したので閉じます
