### ISSUE TITLE
プロジェクトダッシュボードのREADMEで画像表示できない

### ISSUE THREAD

**Issue by orekyuu** [GitThrow/GitThrow#37]
README.mdに`[img!](hoge.png)`みたいにしても画像を表示できずにリンク切れ表示になる。
表示できるようにしたい

**Comment by shift02** [comment]
Markedを使うとかはどうですか？ https://github.com/chjj/marked

**Comment by orekyuu** [comment]
Marked使ってるよー
https://github.com/orekyuu/Workbench2/blob/master/src/main/resources/templates/user/project/index.html#L97
表示されない原因はリンク先に画像がないから。。。

**Comment by shift02** [comment]
なるほど…

**Comment by wreulicke** [comment]
このissueですが以下の内容の実装の必要性があると思われますがどう思われます？

(とりあえずダッシュボードのREADME.mdのみで考える)
- md内のリンクの書き換え  
  - URLマッピングをどこにマッピングする?
    - githubに習ってhogeContext/raw/(ハッシュorブランチ)/path/to/fileみたいな感じ？
- remoteRepositoryのファイルのデータ取得する処理を追加  
  - RemoteRepositoryServiceにinterface追加  
  - 画像に対応するためにReadme.mdの内部の処理を切り出してファイルの内容をByteArrayで返却する？
- byteArrayのまま返却するController？（ごめんなさいここあんまり分からないです。）

**Comment by wreulicke** [comment]
とりあえず一旦、任意のファイルが取り出せるように実装

一旦終了：
　・remoteRepositoryのファイルのデータ取得する処理
残：
　・md内のリンク書き換え
　・生ファイルのURLマッピングおよび対応するController
