### ISSUE TITLE
mvnw testフェイリャー

### ISSUE THREAD

**Issue by Zot201** [GitThrow/GitThrow#7]
mvnw packageから「java.io.UncheckedIOException: java.io.IOException: すでに存在している」が出ました
スタックトレース：http://pastebin.com/raw/XRzXt3LH

テストのタスクに何か設定が必要になるでしょうか

**Comment by orekyuu** [comment]
こちらでもテスト失敗しました。  
テストコード側に問題あるっぽいので修正します

**Comment by orekyuu** [comment]
テストが通ったのでクローズします
